FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
RUN npm run build

COPY . .


## Arguments ##

ARG DATABASE_URL

ARG JWT_SECRET=$q)&'4-&Hg7QD-cN_6;g}KypJP8{RxR!9`PhmF'R
ARG EMAIL_CONFIRM_SECRET=8@rF4Bog34fD3e#CB4m5?4iGgtnQYMB$zc#MLj7P
ARG FORGOT_PASSWORD_SECRET=ir!k7i9ad3@hpf6j?qt9cytN4A9dbJo#@$ej68!C

ARG S3_BUCKET
ARG S3_REGION=eu-central-1
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG S3_ENDPOINT=s3.eu-central-1.wasabisys.com

ARG MAIL_HOST=mail.orb.si
ARG MAIL_USER=noreply@fundl.io
ARG MAIL_PASSWORD
ARG MAIL_FROM=noreply@fundl.io

ARG MAIL_CONFIRM_URL=https://fundl.si/confirm/
ARG MAIL_FORGOT_PASSWORD_URL=https://fundl.si/forgot-password/

ARG SLACK_TOKEN
ARG SLACK_CHANNEL

ARG DISCORD_TOKEN
ARG DISCORD_LOG_CHANNEL_ID


## Environment variables ##

ENV DATABASE_URL $DATABASE_URL

ENV JWT_SECRET $JWT_SECRET
ENV EMAIL_CONFIRM_SECRET $EMAIL_CONFIRM_SECRET
ENV FORGOT_PASSWORD_SECRET $FORGOT_PASSWORD_SECRET

ENV S3_BUCKET $S3_BUCKET
ENV S3_REGION $S3_REGION
ENV S3_ACCESS_KEY $S3_ACCESS_KEY
ENV S3_SECRET_KEY $S3_SECRET_KEY
ENV S3_ENDPOINT $S3_ENDPOINT

ENV MAIL_HOST $MAIL_HOST
ENV MAIL_USER $MAIL_USER
ENV MAIL_PASSWORD $MAIL_PASSWORD
ENV MAIL_FROM $MAIL_FROM

ENV MAIL_CONFIRM_URL $MAIL_CONFIRM_URL
ENV MAIL_FORGOT_PASSWORD_URL $MAIL_FORGOT_PASSWORD_URL

ENV SLACK_TOKEN $SLACK_TOKEN
ENV SLACK_CHANNEL $SLACK_CHANNEL

ENV DISCORD_TOKEN $DISCORD_TOKEN
ENV DISCORD_LOG_CHANNEL_ID $DISCORD_LOG_CHANNEL_ID


EXPOSE 4000

CMD [ "npm", "run", "start:prod" ]